name: Build, Test & Deploy to AKS

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test || echo "No tests defined"

      - name: Build Docker image
        run: docker build -t my-node-app:${{ github.sha }} .

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Push Docker image to ACR
        run: docker tag my-node-app:${{ github.sha }} ${{ secrets.ACR_LOGIN_SERVER }}/my-node-app:${{ github.sha }} && docker push ${{ secrets.ACR_LOGIN_SERVER }}/my-node-app:${{ github.sha }}

  deploy-aks:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS context
        uses: azure/aks-set-context@v3
        with:
          credentials: ${{ secrets.AZURE_CREDENTIALS }}
          cluster-name: ${{ secrets.AKS_CLUSTER_NAME }}
          resource-group: ${{ secrets.AKS_RESOURCE_GROUP }}

      - name: Deploy to AKS
        run: |
          kubectl set image deployment/my-node-app my-node-app=${{ secrets.ACR_LOGIN_SERVER }}/my-node-app:${{ github.sha }}
